const String STATUS_DOWNLOAD_ADDED = "STATUS_DOWNLOAD_ADDED";
const String STATUS_DOWNLOAD_QUEUED = "STATUS_DOWNLOAD_QUEUED";
const String STATUS_DOWNLOAD_PROGRESS = "STATUS_DOWNLOAD_PROGRESS";
const String STATUS_DOWNLOAD_COMPLETED = "STATUS_DOWNLOAD_COMPLETED";
const String STATUS_DOWNLOAD_ERROR = "STATUS_DOWNLOAD_ERROR";
const String STATUS_DOWNLOAD_FOREGROUND_EXCEPTION = "STATUS_DOWNLOAD_FOREGROUND_EXCEPTION";
const String STATUS_DOWNLOAD_CANCELLED = "STATUS_DOWNLOAD_CANCELLED";
const String STATUS_DOWNLOAD_ALL_REMOVED = "STATUS_DOWNLOAD_ALL_REMOVED";

